skip performance test when testing.Short()
AzureAD/microsoft-authentication-library-for-go pull request #429
Opened 2023-06-25 09:21 UTC by hickford

2023-07-06 22:11 UTC, chlowell requested changes
Thanks for doing this. It would be great to have `go test ./...` just do the right thing, however I'm wary of this change by itself because it would enable misconfigured CI runs to succeed without trying these tests. I think we should address this as part of #393

2023-07-08 08:32 UTC, hickford commented
> I'm wary of this change by itself because it would enable misconfigured CI runs to succeed without trying these tests.

@chlowell Good point. Addressed in latest commit by failing test instead of skipping when on CI.

2023-10-24 15:34 UTC, bgavrilMS approved these changes

2023-10-25 09:00 UTC, hickford commented
@chlowell @bgavrilMS Who can merge?

2023-12-07 16:54 UTC, closed without merging