Fix AcquireTokenSilent for ADFS users
AzureAD/microsoft-authentication-library-for-go pull request #446
Opened 2023-08-05 00:19 UTC by chlowell

#426 broke silent auth for ADFS users by requiring a home account ID, which ADFS accounts don't have. This PR restores the v1.0.0 behavior for ADFS by relaxing that requirement, allowing any nonzero account for silent auth. However, I'm uncertain the prior behavior was correct. Because the home account ID for ADFS accounts and tokens is always `""`, the cache matches access tokens on realm and client ID alone, effectively ignoring the user's identity. If the cache has tokens for more than one ADFS user, it will return the first token it considers regardless of the owner. @rayluo @bgavrilMS should the cache match something else in this case such as the local account ID?

2023-08-08 18:27 UTC, bgavrilMS commented
> #426 broke silent auth for ADFS users by requiring a home account ID, which ADFS accounts don't have. This PR restores the v1.0.0 behavior for ADFS by relaxing that requirement, allowing any nonzero account for silent auth. However, I'm uncertain the prior behavior was correct. Because the home account ID for ADFS accounts and tokens is always `""`, the cache matches access tokens on realm, client ID and scope alone, effectively ignoring the user's identity. If the cache has tokens for more than one ADFS user, it will return the first token it considers regardless of the owner. @rayluo @bgavrilMS should the cache match something else in this case such as the local account ID?

How can you tell between 2 users then?!

2023-08-08 18:32 UTC, bgavrilMS commented
No, this is not the correct approach. The id of an ADFS account it based on the `sub` claim in the id token. THis is a mandatory OpenIdConnect claim, guaranteed to be there. 

See https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/main/src/client/Microsoft.Identity.Client/TokenResponseHelper.cs#L48

```csharp
 string homeAccountId = clientInfo?.ToAccountIdentifier() ?? idToken?.Subject;
```

@rayluo  - please confirm if this is the logic that MSAL Py uses.

2023-08-08 18:33 UTC, bgavrilMS requested changes
Use `sub` claim as home account id

2023-08-11 14:29 UTC, bgavrilMS approved these changes

2023-08-11 17:10 UTC, merged

2023-08-15 23:54 UTC, bdwyertech commented on apps/public/public.go
>  		return AuthResult{}, errNoAccount
@chlowell would you guys consider exposing this errNoAccount as ErrNoAccount so us devs can use errors.Is()?  I'm doing a string comparison currently and it feels messy.

https://github.com/bdwyertech/go-az/blob/529fe3c0feca36fc1cab1e74774222f589c9ecc3/pkg/az/auth.go#L117