Added MD file
AzureAD/microsoft-authentication-library-for-go pull request #535
Opened 2024-11-19 14:15 UTC by 4gust

Praposal for logging support for msal-go

2024-11-22 12:00 UTC, bgavrilMS approved these changes
We discussed that we don't need the callback option for 1.18 for now.

2024-12-09 11:28 UTC, bgavrilMS commented on apps/design/logPraposal.md
> +	LogCallback CallbackFunc
We discussed that for golang 1.18 it's ok to not have any logging.

2024-12-19 14:16 UTC, bgavrilMS commented on apps/logger/logger.go
> +func New(slogLogger *slog.Logger) (*Logger, error) {
I am not sure about this. The moment we put slog in the public API surface, Azure SDK will not be able to use MSAL SDK.

2024-12-19 14:19 UTC, bgavrilMS commented on apps/logger/logger.go
> +func New(slogLogger *slog.Logger) (*Logger, error) {
See with https://github.com/AzureAD/microsoft-authentication-library-for-go/blob/main/apps/design/release.md for testing with azure sdk

2025-01-07 01:41 UTC, chlowell requested changes

2025-01-07 01:41 UTC, chlowell commented on apps/confidential/confidential_121_plus.go
> +func WithLogger(l interface{}) Option {
`interface{}` effectively disables compiler type checking here, making this function difficult to use and turning a class of build errors into runtime errors--not great. This option only works if `l` is a `*slog.Logger`; should that be the parameter's type?

2025-01-07 01:41 UTC, chlowell commented on apps/internal/logger/logger_121_plus.go
> +		context.Background(),
this must be the Context of the encompassing operation i.e., the caller must provide it

2025-01-07 01:41 UTC, chlowell commented on apps/internal/logger/logger_121_plus.go
> +	return nil, fmt.Errorf("invalid input for Go 1.21+; expected *slog.Logger")
then shouldn't the parameter be of type `*slog.Logger`?

2025-01-07 01:41 UTC, chlowell commented on apps/design/logging.md
> +   - User should pass *nil* to `logger.New(nil)`
Users can't call `logger.New` because it's in an `internal` package. Is this doc or the implementation incorrect?

2025-01-07 01:41 UTC, chlowell commented on apps/confidential/confidential_121_plus.go
> +			return
This won't do. The caller has every reason to believe the call succeeded and won't find out something went wrong until they notice the lack of logging and/or this line in stdout. Returning the error is the right thing to do but impossible here. So, this needs a redesign. Off the top of my head, I suppose the alternatives are:
1. make it impossible for this function to receive an error i.e., make it impossible for `logger.New` to return an error
2. separate logger construction from this function i.e., have users call `logger.New` themselves, check its error, pass the logger to `WithLogger`

2025-01-07 10:32 UTC, AndyOHart commented on apps/tests/devapps/logger/logger_sample.go
Was made for testing purposes but can remove

2025-01-07 10:34 UTC, AndyOHart commented on apps/design/logging.md
> +   - User should pass *nil* to `logger.New(nil)`
This doc is the old proposal that was updated for the newer implementation, but the new implementation has since changed so will have to update this document once we are happy with the implementation

2025-01-07 13:45 UTC, bgavrilMS commented on apps/confidential/confidential_121_plus.go
> +			return
Option 2 is not great for developer experience though. The app developer would be exposed to an unnecessary abstraction.

Option 1 looks great. If not possible, would Option 3 be feasible - return the error in the ConfidentialClientApplication / ManagedIdentityApplication builder ?

2025-01-07 16:00 UTC, bgavrilMS commented on apps/confidential/confidential_121_plus.go
> +			return
I don't see any updates in the PR

2025-01-07 17:41 UTC, chlowell commented on apps/confidential/confidential_121_plus.go
> +			return
The question I'm really circling around here is, do you imagine ever supporting logging via something other than slog? Answering this points the way forward. If you want to support only slog, you can simply have `WithLogger(logger slog.Logger)`, you don't need an abstraction layer like `LoggerInterface`, and you get my option 1 for free because this `WithLogger` can't produce an error. If you want to maintain the possibility of easy non-slog logging, then you need to expose `LoggerInterface`, have `WithLogger` take one of those, and decide what to do when someone calls `WithLogger(nil)`

2025-01-07 18:04 UTC, AndyOHart commented on apps/confidential/confidential_121_plus.go
> +			return
I think the main issue or maybe just a misunderstanding on how best to handle it, is for go versions < 1.21
The LoggerInterface i think makes it simple to handle having something that supports 1.21 and also not causing an issue with < 1.21. 
If we remove the loggerInterface would it not cause the code to become a bit more messy and having to use build tags directly inside the confidential.go class, and having clientOptions defined in both places?

2025-01-09 13:40 UTC, bgavrilMS commented on apps/confidential/confidential_121_plus.go
> +func WithLogger(l *slog.Logger) Option {
Yes, this is a good interface. Not sure about the comment though ... Pls add a link to slog and some details about how a log consumer would set this up.

2025-01-09 13:41 UTC, bgavrilMS commented on apps/design/logging.md
> +A sample of the logger can be found in the following location:
I would prefer a wiki page or just put the code here. Dev apps are not samples. Samples have their own repos etc.

2025-01-09 13:48 UTC, bgavrilMS reviewed
LGTM if this works. Not signing off as there is some work to be done.

2025-01-09 16:42 UTC, AndyOHart commented on apps/internal/logger/logger.go
> +//go:build go1.21
No this should just be included in the build if Go version is 1.21 or higher

2025-01-09 16:42 UTC, AndyOHart commented on apps/design/logging.md
> +A sample of the logger can be found in the following location:
I will remove this once PR is approved, as I am using it for some testing currently, but will remove before merge

2025-01-09 20:04 UTC, AndyOHart commented on apps/confidential/confidential.go
> +	opts.logger.Log(context.Background(), logger.Info, "Created confidential client", logger.Field("clientID", clientID))
Will remove this once the PR is approved as it is here now for testing

2025-01-09 20:04 UTC, AndyOHart commented on apps/confidential/confidential.go
> +		logger:                   nil,
Updated

2025-01-09 20:06 UTC, AndyOHart commented on apps/internal/logger/logger.go
> +		defaultLogger := slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{}))
Updated

2025-01-09 20:06 UTC, AndyOHart commented on apps/internal/logger/logger.go
> +type Logger struct {
Updated

2025-01-09 20:06 UTC, AndyOHart commented on apps/internal/logger/logger_test.go
> +	expectedMessages := []string{
Updated

2025-01-09 20:07 UTC, AndyOHart commented on apps/confidential/confidential_121_plus.go
> +func WithLogger(l *slog.Logger) Option {
Updated

2025-01-09 21:40 UTC, chlowell reviewed
Are you adding tests for `confidential.Client` as well i.e., testing that `confidential.New(WithLogger(...))` constructs a Client that writes logs?

Is the same API coming for `public.Client` in another PR?

2025-01-09 21:40 UTC, chlowell commented on apps/confidential/confidential_121_plus.go
> +	"github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/slog"
When pkgsite renders docs for `WithLogger`, it creates a link to the definition of the parameter's type i.e., `slog.Logger`. If that type is defined in your `internal/slog` package, the doc link will point there, meaning anyone who clicks that link ends up at docs for an internal package they can't reference. Of course that package references types from `logs/slog` and therefore its docs link in turn to that package, but you can avoid linking to your internal package by importing `logs/slog` here:
```suggestion
	"log/slog"
```
(this doesn't break the build because the compiler is smart enough to realize that your `internal/slog.Logger` is the same type as `logs/slog.Logger`)

2025-01-09 21:40 UTC, chlowell commented on apps/confidential/confidential_121_plus.go
How about `with_logger.go`?

2025-01-09 21:40 UTC, chlowell commented on apps/internal/slog/logger.go
> +func Field(key string, value any) any {
Do you need this?

2025-01-09 21:40 UTC, chlowell commented on apps/internal/slog/logger_121_below.go
> +	Debug Level = iota
```suggestion
	LevelDebug Level = iota
```
etc. These symbols must be the same for all supported versions of Go

2025-01-09 21:40 UTC, chlowell commented on apps/internal/slog/logger_test.go
> +	if logInstance == nil {
But is `logInstance` the default logger?

2025-01-09 21:41 UTC, chlowell commented on apps/confidential/confidential_121_plus.go
> +func WithLogger(l *slog.Logger) Option {
🤔 the important thing about this option is that it enables logging, not that it enables specifying a custom Logger. The parameter type itself expresses that. So I think this comment only needs to cover that this option enables logging and when `l` is nil, Client will use `slog.Default()`, which will lead to a panic when `slog.Default()` returns nil. You don't need to show how to call this function or explicitly link to the slog docs. pkgsite will create a link to the slog docs on the parameter type

2025-01-09 22:49 UTC, AndyOHart commented on apps/confidential/confidential_121_plus.go
> +func WithLogger(l *slog.Logger) Option {
Updated

2025-01-10 12:31 UTC, AndyOHart approved these changes
PR was created by Nilesh but it also seems good to me from working on it

2025-01-10 12:38 UTC, AndyOHart commented on apps/confidential/confidential_121_plus.go
> +	"github.com/AzureAD/microsoft-authentication-library-for-go/apps/internal/slog"
Interesting to know thanks!

2025-01-17 19:28 UTC, chlowell commented
How will we handle logging PII? Another argument to `WithLogger`, or could we use slog to mark a message or part of a message as PII and leave handling that up to the application?

2025-01-24 21:33 UTC, chlowell commented on apps/internal/slog/logger_121_below.go
> +type NopHandler struct{}
not a blocker but consider defining this once, in a separate file e.g. `nop_handler.go` with no build constraint

2025-01-24 21:33 UTC, chlowell commented on apps/managedidentity/managedidentity_with_logger_test.go
> +func (h *FilteredBufferHandler) Handle(ctx context.Context, record slog.Record) error {
you could add a `level` field to BufferHandler instead of defining a second type

2025-01-24 21:33 UTC, chlowell commented on apps/managedidentity/managedidentity_with_logger_test.go
> +	// Set up mock client
please forgive nitpicking: I'd remove these comments because the code clearly says what it does

2025-01-24 21:33 UTC, chlowell commented on apps/managedidentity/managedidentity_with_logger_test.go
> +	bufferHandler := &BufferHandler{}
I'd delete this test because it doesn't add any coverage and can't catch any logging bug. It doesn't mutate the handler or pass it to another function, so of course the handler has the same state at the end of the test

2025-01-27 11:25 UTC, bgavrilMS commented on apps/managedidentity/managedidentity_with_funcs.go
> +func WithPiiLogging() ClientOption {
I would prefer to have a `WithLogger(l *slog.Logger, piiEnabled bool)` single API because: 

1. It reduces the number of methods that IDEs "auto-complete" display. We had some developer feedback on other MSALs that we expose too many options already...
2. Consistency with other MSALs

2025-01-28 15:19 UTC, AndyOHart commented on apps/managedidentity/managedidentity_with_funcs.go
> +func WithPiiLogging() ClientOption {
Updated

2025-01-31 22:00 UTC, chlowell commented on apps/internal/slog/nop_handler.go
> +type NopHandler struct{}
I meant you can put this type and all its methods in the same file, built unconditionally, so you don't have to duplicate them for both version ranges. You would have to define some additional stub types for versions < 1.21. One uninteresting line doesn't deserve its own file, so if you don't want to define the stub types, I suggest simply duplicating this definition as you did previously

2025-01-31 22:00 UTC, chlowell commented on apps/internal/slog/logger_test.go
> +	if logInstance == nil {
The above test calls `New` with the same arguments and will panic when the return is nil. So, you may as well delete this test

2025-01-31 22:00 UTC, chlowell commented on apps/managedidentity/managedidentity_with_funcs.go
options.go?

2025-01-31 22:00 UTC, chlowell commented on apps/managedidentity/managedidentity.go
> +	c.logger.Log(ctx, slog.LevelInfo, "Managed Identity", slog.String("source", string(c.source)))
This will log the source upon every token request. While it's definitely helpful to log the source, you really only want to do so once because the value is immutable. I guess you placed this here instead of in `New` because `New` doesn't get context? This is pretty awkward 😆. I suppose the possible solutions are
- create a context (with timeout) in `New` for logging the source
- log this here but only once per process (see [sync.Once](https://pkg.go.dev/sync#Once))

Option 2 looks better to me

2025-01-31 22:00 UTC, chlowell commented on apps/managedidentity/managedidentity_with_logger_test.go
> +	headers.Set("www-authenticate", "Basic realm=/path/to/secret.key")
Is this necessary?

2025-01-31 22:00 UTC, chlowell commented on apps/managedidentity/managedidentity_with_logger_test.go
> +func TestClientLogging_CustomHandler(t *testing.T) {
This is nearly identical to the above test. Really it just verifies that `AcquireToken` logs its message at a level higher than Debug. Couldn't you do that more simply by having the above test also verify the level directly?

2025-02-07 00:32 UTC, chlowell commented on apps/managedidentity/managedidentity_with_logger_test.go
> +//go:build go1.21
license

2025-02-07 00:32 UTC, chlowell commented on apps/managedidentity/managedidentity.go
> +		client.logger.Log(context.Background(), slog.LevelInfo, "Managed Identity", slog.String("source", string(client.source)))
logging may entail network I/O, so this could still block indefinitely depending on the handler implementation. It would be better to do this in `AcquireToken`

2025-02-12 15:35 UTC, AndyOHart commented on apps/internal/slog/nop_handler.go
> +type NopHandler struct{}
As discussed, reverting to how it was as this may be too messy

2026-05-26 10:32 UTC, closed without merging